
<html>
<head>
    <style type="text/css">
        .container{margin-top:30px;}
    </style>
    <script type="text/javascript" src="/public/js/lib/jquery-1.11.1.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
    
</head>
<body>
    <div class="container">

            <fieldset>
                <legend>Task 1</legend>
                <p><div class="row">
                    <div class="col-md-2"><label>1. Input email: </label></div>
                    <div class="col-md-4"><a class="btn btn-default" href="<?php echo $this->url(array('controller' => 'index', 'action' => 'practice1')); ?>">Go to</a></div>
                </div></p>

                <p><div class="row">
                    <div class="col-md-2"><label>2. File extension: </label></div>
                    <div class="col-md-4"><a class="btn btn-default" href="<?php echo $this->url(array('controller' => 'index', 'action' => 'practice2')); ?>">Go to</a></div>
                </div></p>

                <p><div class="row">
                    <div class="col-md-2"><label>3. Show content of file and high-light keyword: </label></div>
                    <div class="col-md-4"><a class="btn btn-default" href="<?php echo $this->url(array('controller' => 'index', 'action' => 'practice3')); ?>">Go to</a></div>
                </div></p>
                
    </div>
</body>
</html>


<!--<div class="row">
                    <div class="col-md-2"><label for="email">1. Input email: </label></div>
                    <div class="col-md-4"><input class="form-control" type="email" id="email" name="email" required></div>
                    <div class="col-md-2"></div>
                    <div class="col-md-2"><input class="btn btn-success" class="btn btn-success" type="submit" name="submit" value="Submit"></div>
                </div>
                </p>
        </form>
                <p>
                <div class="row">
                    <div class="col-md-2"><label for="file">2. Choose file: </label></div>
                    <div class="col-md-4"><input class="form-control" type="file" id="file" name="file"></div>
                    <div class="col-md-2"><div id="info_file" name="info_file"></div></div>
                    </div>
                    <div class="col-md-2"><button id="checkFile" class="btn btn-success">Check</button></div>
                </div>
                </p>
        <form>
                <p>
                <div class="row">
                    <div class="col-md-2"><label for="file">3. Choose file: </label></div>
                    <div class="col-md-4"><input class="form-control" type="file" id="txt" name="txt"></div>
                    <div class="col-md-2"><label>Keyword: </label></div>
                    <div class="col-md-4"><input class="form-control" type="text" id="key" name="key"></div>
                    <div id="err"></div>
                </div>
                </p>
                <div class="row" align="center">
                    <input class="btn btn-success" type="button" name="showText" value="Show">
                </div>
            </fieldset>
        </form>
        -->