
<html>
<head>
    <style type="text/css">
        .container{margin-top:30px;}
    </style>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
    <script type="text/javascript">

    </script>
</head>
<body>
    <div class="container">
            <form>
                <div class="row">
                    <div class="col-md-2"><label for="email">1. Input email: </label></div>
                    <div class="col-md-4"><input class="form-control" type="email" id="email" name="email" required></div>
                    <div class="col-md-2"></div>
                    <div class="col-md-2"><input class="btn btn-success" class="btn btn-success" type="submit" name="submit" value="Submit"></div>
                </div>
            </form>
            <div class="row"><a href="<?php echo $this->url(array('controller' => 'index','action'=>'index')); ?>">Back</a></div>
    </div>
</body>
</html>
